services:
  - type: web
    name: chatbot-demo
    env: "php"
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
    startCommand: php artisan serve --host 0.0.0.0 --port $PORT
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: "production"
      - key: APP_DEBUG
        value: "true"
      - key: APP_KEY
        value: "base64:2qkZw6izXeK2aws6GdoZ5D+/J/bL3X5k0ZSHdO5U3wM="
